# API for registration
POST http://127.0.0.1:8000/api/account/register/
Content-Type: application/json

{
    "password": "Student@123", 
    "email": "student6@yopmail.com", 
    "profile": {"role": "student"}
}

###

#  API to get token if we give correct credientials
POST http://127.0.0.1:8000/api/account/token/
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "User@123"
}

###

#  API to get new access token when I give refresh token
POST http://127.0.0.1:8000/api/account/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyNTI1ODIzNywiaWF0IjoxNzI1MTcxODM3LCJqdGkiOiI5MzU0MzIxYzg1NTg0Y2M3OTUzNDIyZTU0ZGEzZThlOSIsInVzZXJfaWQiOjR9.DZ8HbdwxQ8ucM-0YRI_EDh6IzyuEFQ_XYPMDJNEIq7w"
}