# API for registration
POST http://127.0.0.1:8000/api/account/register/
Content-Type: application/json

{
    "password": "Student@123", 
    "email": "student6@yopmail.com", 
    "profile": {"role": "student"}
}

###

#  API to get token if we give correct credientials
POST http://127.0.0.1:8000/api/account/token/
Content-Type: application/json

{
    "email": "student1@gmail.com",
    "password": "Student@123"
}

###

#  API to get new access token when I give refresh token
POST http://127.0.0.1:8000/api/account/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyNTI1ODIzNywiaWF0IjoxNzI1MTcxODM3LCJqdGkiOiI5MzU0MzIxYzg1NTg0Y2M3OTUzNDIyZTU0ZGEzZThlOSIsInVzZXJfaWQiOjR9.DZ8HbdwxQ8ucM-0YRI_EDh6IzyuEFQ_XYPMDJNEIq7w"
}

####

GET http://127.0.0.1:8000/api/account/user-status/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI1MjUyNDI5LCJpYXQiOjE3MjUyNTIxMjksImp0aSI6IjAwYzM5ZDI2Mjg0NzRjZmY5OGZlYTliZjk2NGE4MDhjIiwidXNlcl9pZCI6MSwiaWQiOjEsInJvbGUiOiJhZG1pbiIsImlzX2FjdGl2ZSI6dHJ1ZX0.N86ROBmOyGxAX_35uu7kP8bmPyIX9pvXHxSp4mfkA5I
Content-Type: application/json